- name: install epel-release
  yum:
    name: epel-release
    state: latest

- name: add docker repo
  yum_repository:
    name: Docker Repository
    description: Docker Repository
    baseurl: https://yum.dockerproject.org/repo/main/centos/7/
    gpgcheck: yes

- name: install packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker
    - python2-pip
    - python2-devel
    - gcc
