---
- name: install packages
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - python-pip
    - python-dev

- name: add docker key
  apt_key:
    url: "https://apt.dockerproject.org/gpg"
    state: present

- name: add docker repo
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo debian-{{ ansible_distribution_release }} main
    state: present

- name: install docker packages
  apt:
    name: "docker-engine={{ docker_version }}~ce-0~debian-jessie"
    update_cache: yes
    state: present
